import {getSongSetting,refreshSongSettings,getSongStatus,subscribeSongStatus} from '../native/song-publisher.js';
import {readLyricSetting,writeLyricSetting as updateLyric} from '../native/lyric-settings.js';
const bool=(key,fallback=true)=>localStorage.getItem(key)===null?fallback:localStorage.getItem(key)!=='false';
function copy(text){const el=document.createElement('textarea');el.value=text;el.style.cssText='position:fixed;opacity:0';document.body.appendChild(el);el.select();document.execCommand('copy');el.remove();}
export function makeSettings(){
 const root=document.createElement('div');root.className='obs-suite-settings';
 if(!document.getElementById('obs-suite-settings-style')){
  const style=document.createElement('style');style.id='obs-suite-settings-style';style.textContent=`.obs-suite-settings{padding:20px;color:var(--md-accent-color-secondary,inherit);font:14px/1.65 inherit}.obs-suite-settings h2{margin:0 0 6px;font-size:23px;color:var(--md-accent-color,inherit)}.obs-suite-settings h3{font-size:17px;margin:0 0 12px}.obs-suite-settings .suite-note{opacity:.7;font-size:12px;margin:5px 0 12px}.obs-suite-settings section,.obs-suite-settings details{padding:16px;margin-top:15px;border-radius:14px;background:rgba(var(--md-accent-color-rgb,128,128,128),.065);border:1px solid rgba(var(--md-accent-color-rgb,128,128,128),.12)}.obs-suite-settings label.suite-option{display:flex;align-items:center;gap:9px;margin:9px 0}.obs-suite-settings input[type=checkbox]{accent-color:var(--md-accent-color)}.obs-suite-settings select,.obs-suite-settings input[type=number]{color:inherit;background:transparent;border:1px solid #8886;border-radius:7px;padding:5px 8px;max-width:130px}.obs-suite-settings .suite-url{display:flex;gap:8px}.obs-suite-settings .suite-url input{flex:1;min-width:0;color:inherit;background:transparent;border:1px solid #8886;border-radius:7px;padding:7px}.obs-suite-settings button{cursor:pointer;color:inherit;border:1px solid #8886;background:transparent;border-radius:7px;padding:5px 10px}.obs-suite-settings summary{cursor:pointer;font-size:16px}.obs-suite-settings [data-lyricbar-obs]{display:none!important}`;document.head.appendChild(style);
 }
 const title=document.createElement('h2');title.textContent='OBS 直播套件';
 const description=document.createElement('div');description.className='suite-note';description.textContent='统一管理歌曲信息、封面柔光、动态柱条和小词栏。两个 OBS 源共用 Material You 动态配色。';root.append(title,description);
 const checkbox=(parent,label,value,change)=>{const row=document.createElement('label');row.className='suite-option';const input=document.createElement('input');input.type='checkbox';input.checked=value;input.addEventListener('change',()=>change(input.checked));row.append(input,label);parent.append(row);return input;};
 checkbox(root,'启用 OBS 直播套件',bool('obs-suite-enabled'),value=>{localStorage.setItem('obs-suite-enabled',String(value));window.__lyricBarObs?.refreshEnabled?.();refreshSongSettings();});
 function section(name,note){const el=document.createElement('section'),heading=document.createElement('h3');heading.textContent=name;el.append(heading);if(note){const text=document.createElement('div');text.className='suite-note';text.textContent=note;el.append(text);}root.append(el);return el;}
 function address(parent,url){const row=document.createElement('div');row.className='suite-url';const input=document.createElement('input');input.type='text';input.readOnly=true;input.value=url;input.setAttribute('aria-label','OBS 浏览器源地址');input.onclick=()=>input.select();const button=document.createElement('button');button.type='button';button.textContent='复制地址';button.onclick=()=>copy(url);row.append(input,button);parent.append(row);}
 function number(parent,label,value,min,max,step,change){const row=document.createElement('label');row.className='suite-option';const input=document.createElement('input');input.type='number';input.value=String(value);input.min=String(min);input.max=String(max);input.step=String(step);input.setAttribute('aria-label',label);input.onchange=()=>{const number=Math.max(min,Math.min(max,Number(input.value)||0));input.value=String(number);change(number);};row.append(label,input);parent.append(row);}
 function choice(parent,label,value,options,change){const row=document.createElement('label');row.className='suite-option';row.append(label);const select=document.createElement('select');select.setAttribute('aria-label',label);for(const [key,text]of options){const option=document.createElement('option');option.value=String(key);option.textContent=text;select.append(option);}select.value=String(value);select.onchange=()=>change(select.value);row.append(select);parent.append(row);}
 const song=section('歌曲信息与封面','分体卡片布局；播放器主体在 500px 浏览器源中宽 452px。');
 for(const [key,label]of [['enabled','在 OBS 显示歌曲信息'],['cover-glow','封面发光'],['progress','显示播放进度'],['rhythm','启用动态柱条'],['hide-paused','暂停时隐藏歌曲组件']])checkbox(song,label,getSongSetting(key),value=>{localStorage.setItem('obs-stream-song-'+key,String(value));refreshSongSettings();});
 for(const [key,label]of [['card-radius','歌曲卡片圆角（px）'],['cover-radius','封面圆角（px）']])number(song,label,getSongSetting(key),0,100,1,value=>{localStorage.setItem('obs-stream-song-'+key,String(value));refreshSongSettings();});
 const fpsRow=document.createElement('label');fpsRow.className='suite-option';fpsRow.append('动态柱条帧率');const select=document.createElement('select');select.setAttribute('aria-label','动态柱条帧率');for(const value of [10,15,20,30]){const option=document.createElement('option');option.value=String(value);option.textContent=value+' FPS';select.append(option);}select.value=String(getSongSetting('rhythm-framerate'));select.onchange=()=>{localStorage.setItem('obs-stream-song-rhythm-framerate',select.value);refreshSongSettings();};fpsRow.append(select);song.append(fpsRow);
 const rhythmNote=document.createElement('div');rhythmNote.className='suite-note';rhythmNote.textContent='柱条为播放状态驱动的动态视觉效果。隐藏或暂停时停止更新。';song.append(rhythmNote);address(song,__SONG_VIEW_URL__);
 const songStatus=document.createElement('div');songStatus.className='suite-note';songStatus.textContent=getSongStatus();song.append(songStatus);subscribeSongStatus(value=>{songStatus.textContent=value;});
 const lyric=section('OBS 小词栏','短句自适应，长句达到上限后换行并向上展开；保留宽高形变和暂停淡出。');
 checkbox(lyric,'在 OBS 显示小词栏',bool('lyric-bar-obs-enabled'),value=>{localStorage.setItem('lyric-bar-obs-enabled',String(value));window.__lyricBarObs?.refreshEnabled?.();});
 number(lyric,'最大宽度（px，0 自动跟随播放器）',Number(readLyricSetting('obs-max-width','0'))||0,0,2000,1,value=>updateLyric('obs-max-width',value));
 number(lyric,'宽高形变时长（ms）',Number(readLyricSetting('obs-morph-duration','500'))||500,100,2000,50,value=>updateLyric('obs-morph-duration',value));
 const storedRadius=readLyricSetting('obs-radius','16'),radius=Number(storedRadius);
 number(lyric,'小词栏圆角（px）',Number.isFinite(radius)?Math.max(0,Math.min(100,radius)):16,0,100,1,value=>updateLyric('obs-radius',value));
 address(lyric,__LYRIC_VIEW_URL__);const lyricStatus=document.createElement('div');lyricStatus.className='suite-note';lyricStatus.dataset.lyricbarObsStatus='';lyricStatus.textContent=window.__lyricBarObs?.status||'等待初始化';lyric.append(lyricStatus);
 const details=document.createElement('details'),summary=document.createElement('summary');summary.textContent='OBS 歌词排版与逐字动画';details.append(summary);root.append(details);
 const note=document.createElement('div');note.className='suite-note';note.textContent='首次继承已有词栏设置，之后独立保存；这里的修改不影响原 LyricBar。';details.append(note);
 number(details,'歌词字号（px）',Number(readLyricSetting('lyric-font-size','20')),12,64,1,value=>updateLyric('lyric-font-size',value));
 for(const [key,label,fallback]of [['show-translation','显示翻译',true],['show-romaji','显示罗马音',false],['use-karaoke-lyrics','启用逐字歌词',true],['first-line-bold','主歌词加粗',false]])checkbox(details,label,readLyricSetting(key,String(fallback))==='true',value=>updateLyric(key,value));
 choice(details,'文字对齐',readLyricSetting('text-align','left'),[['left','左对齐'],['center','居中'],['right','右对齐']],value=>updateLyric('text-align',value));
 choice(details,'逐字动画帧率',readLyricSetting('karaoke-framerate','0'),[[0,'不限'],[30,'30 FPS'],[60,'60 FPS'],[120,'120 FPS']],value=>updateLyric('karaoke-framerate',Number(value)));
 number(details,'文字不透明度（%）',Number(readLyricSetting('opacity','100')),0,100,1,value=>updateLyric('opacity',value));
 number(details,'歌词时间偏移（ms）',Number(readLyricSetting('lyric-offset','0')),-5000,5000,50,value=>updateLyric('lyric-offset',value));
 const connection=section('本机连接','当前两个 OBS 地址和场景位置继续沿用。连接服务在本机后台运行。');const serviceState=document.createElement('div');serviceState.className='suite-note';serviceState.textContent='连接状态待检查';const check=document.createElement('button');check.type='button';check.textContent='启动 / 检查连接';check.onclick=async()=>{try{await window.__obsSuiteRuntime.prepare(true);const response=await fetch(__HEALTH_URL__);if(!response.ok)throw Error();const state=await response.json();serviceState.textContent=state.service==='lyricbar-obs'?'本机连接正常':'连接服务响应不匹配';}catch{serviceState.textContent='本机服务未连接。请安装 Node.js 20+ 后重试；启动错误见下方。';}};connection.append(check,serviceState);
 const links=document.createElement('div');links.className='suite-note';for(const [label,url]of [['源码仓库','https://github.com/LilycleHeart/OBSStreamSuite'],['问题反馈','https://github.com/LilycleHeart/OBSStreamSuite/issues']]){const button=document.createElement('button');button.type='button';button.textContent=label;button.onclick=()=>betterncm.ncm.openUrl(url);links.append(button,' ');}root.append(links);return root;
}
